
name: Hello world action 

on: 
  push:

  workflow_dispatch:
    inputs:
      who-to-greet:  # id of input
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: malachiCunliffe/github-action-hello-world@v1.4
        with:
          who-to-greet: ${{inputs.who-to-greet || 'World'}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"